/**
 * Procedure Generation Prompts
 *
 * Generates detailed step-by-step work instructions for a specific
 * BPMN activity (TASK type). This is the most granular deliverable —
 * what a person actually DOES at their desk.
 */

export const PROCEDURE_GEN_SYSTEM = `You are a senior BPM consultant generating a detailed Work Procedure (Procedimiento) for a specific business activity.

A procedure is a step-by-step instruction document that tells someone EXACTLY how to perform a task. It must be specific enough that a new employee could follow it on day 1.

Return JSON:
{
  "processName": "Parent process this activity belongs to",
  "activityName": "The specific activity/task",
  "procedureCode": "PR-XXX-001 format",
  "objective": "What this procedure achieves",
  "scope": "When and where this procedure applies",
  "responsible": "Role that executes this procedure",
  "frequency": "How often (daily, per request, weekly, etc.)",
  "prerequisites": ["What must be true before starting"],
  "steps": [
    {
      "stepNumber": 1,
      "action": "Verb-first action (e.g., 'Abrir el módulo de compras en SAP')",
      "responsible": "Who does this step",
      "description": "Detailed how-to explanation",
      "inputs": ["Documents/data needed"],
      "outputs": ["Documents/data produced"],
      "systems": ["Software/tools used"],
      "controls": ["Verification points, quality checks"],
      "exceptions": [
        { "condition": "If X happens", "action": "Then do Y" }
      ],
      "estimatedTime": "~5 min",
      "notes": "Tips, warnings, common mistakes"
    }
  ],
  "definitions": [
    { "term": "Technical term", "definition": "What it means" }
  ],
  "relatedDocuments": ["Reference documents, forms, policies"],
  "indicators": [
    { "name": "KPI name", "formula": "How measured", "target": "Expected value" }
  ],
  "revisionHistory": [
    { "version": "1.0", "date": "2026-03-23", "description": "Initial version generated by aiprocess.me AI" }
  ],
  "gaps": ["Information missing to complete this procedure"],
  "overallConfidence": 0.0-1.0
}

Rules:
- Steps must start with a VERB (Abrir, Verificar, Registrar, Enviar, Aprobar...)
- Be SPECIFIC: "Abrir SAP transaccion ME21N" not "Abrir el sistema"
- Include exception handling for each step where relevant
- Controls are quality checkpoints — what to verify before moving on
- If information is missing, still generate the procedure structure but mark gaps
- Estimated time should be realistic for a trained employee
- Output in the SAME LANGUAGE as the input context`;

export const PROCEDURE_GEN_USER = (context: {
  processName: string;
  activityName: string;
  activityLane?: string;
  processDescription?: string;
  bpmnContext?: string; // Surrounding BPMN nodes for context
  transcriptExcerpts?: string[];
  documentExcerpts?: string[];
  systems?: string[];
  roles?: string[];
}) => {
  const parts: string[] = [];

  parts.push(`PROCESS: ${context.processName}`);
  parts.push(`ACTIVITY: ${context.activityName}`);
  if (context.activityLane) parts.push(`LANE/RESPONSIBLE: ${context.activityLane}`);
  if (context.processDescription) parts.push(`PROCESS DESCRIPTION: ${context.processDescription}`);

  if (context.bpmnContext) {
    parts.push(`\nBPMN CONTEXT (surrounding activities):\n${context.bpmnContext}`);
  }

  if (context.systems && context.systems.length > 0) {
    parts.push(`\nSYSTEMS USED IN THIS PROCESS:\n${context.systems.map((s) => `- ${s}`).join("\n")}`);
  }

  if (context.roles && context.roles.length > 0) {
    parts.push(`\nROLES IN THIS PROCESS:\n${context.roles.map((r) => `- ${r}`).join("\n")}`);
  }

  if (context.transcriptExcerpts && context.transcriptExcerpts.length > 0) {
    parts.push(`\nTRANSCRIPT EXCERPTS (where this activity was discussed):\n${context.transcriptExcerpts.join("\n---\n")}`);
  }

  if (context.documentExcerpts && context.documentExcerpts.length > 0) {
    parts.push(`\nDOCUMENT EXCERPTS:\n${context.documentExcerpts.join("\n---\n")}`);
  }

  return `${parts.join("\n")}

Generate a detailed work procedure for the activity "${context.activityName}" within the process "${context.processName}". Include step-by-step instructions, exception handling, controls, and KPIs.`;
};
